const CART_ACTIONS_TYPES = {
   TOGGLE_CART_HIDDEN : 'TOGGLE_CART_HIDDEN',
   ADD_iTEM_TO_CART : 'ADD_iTEM_TO_CART',
   REMOVE_ITEM_FROM_CART : 'REMOVE_ITEM_FROM_CART',
   DELETE_ITEM_FROM_CART : 'DELETE_ITEM_FROM_CART' 
};

export default CART_ACTIONS_TYPES;